name: windows-build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  windows-build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        solution_path: [./project/vc/vsf_linux.sln, ./project/vc_git/vsf_linux.sln, ./project/vc_git_hostsock/vsf_linux.sln, ./project/vs_openssl/vsf_linux.sln]
        build_config: [Debug]

    steps:
    - name: Checkout With Submodule
      uses: actions/checkout@v2
      with:
        submodules: true # without recursive
    - name : update vsf submodules
      run: |
        cd vsf
        git submodule update --init

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{matrix.solution_path}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{matrix.build_config}} ${{matrix.solution_path}}

